services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/usr/src/app
      - core_modules:/usr/src/app/node_modules
    restart: always
    ports:
      - "4000:3000"
    env_file:
      - ./env/.env
      - ./env/core.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: postgres
    container_name: db_postgres_container
    restart: always
    env_file:
      - ./env/db.env
    ports:
      - "5432:5432"
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_postgres_data:
  core_modules:
